version: '3.8'
services:
  backend:
    build:
      context: ..
      dockerfile: Dockerfile.backend

    ports:
      - '3000:3000'
    environment:
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_HOST=db
      - DATABASE_SYNCHRONIZE=false
    depends_on:
      - db
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  #frontend:
  #  build:
  #    context: ./frontend
  #    dockerfile: Dockerfile.frontend
  #  ports:
  #    - '3001:3000'
  #  depends_on:
  #    - backend
volumes:
  postgres_data:

